### ISSUE TITLE
Fast mode fixes not applied to audio frame pumping

### ISSUE THREAD

**Issue by Starbuck5** [SAV1-org/SAV1#12]
I.e. changes made to video frame in https://github.com/SAV1-org/SAV1/commit/4f7c93955464e6b1a4b3798c37a3d9f672a3d50f

**Comment by ElijahCirioli** [comment]
Why would you open this?

**Comment by Starbuck5** [comment]
I assumed you wanted to me to fix it, and I didn't want to do it just that second. So I opened an issue as a reminder.

**Comment by ElijahCirioli** [comment]
I told you I was gonna fix it.

**Comment by Starbuck5** [comment]
If you say so...
